In [1]:
import numpy as np

In [2]:
# 브로드 캐스팅
nums = np.array([10, 20, 30, 40])

In [4]:
nums2 = nums * 2 
print(nums2)

[20 40 60 80]


In [5]:
nums3 = nums - 5
print(nums3)

[ 5 15 25 35]


In [6]:
data = np.column_stack(([10, 20, 30], [1, 2, 3], [100, 200, 300]))
print(data)

[[ 10   1 100]
 [ 20   2 200]
 [ 30   3 300]]
