In [2]:
import numpy as np

In [3]:
nums = np.array([1, 2, 3, 4]) 
print(nums) # 1차원 배열

[1 2 3 4]


In [4]:
nums2 = nums.reshape(2, 2)
print(nums2) # 2차원 배열

[[1 2]
 [3 4]]


In [5]:
nums3 = np.array([[[1, 2, 3], [4,5,6]], [[7,8,9], [10, 11, 12]]])
print(nums3) # 3차원 배열

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [12]:
nums4 = np.reshape(10, 10)
print(nums4)

ValueError: cannot reshape array of size 1 into shape (10,)